API_TITLE = "Intersection Simulation API"
API_VERSION = "1.0.0"

API_PREFIX = "/api/v1"
INTERSECTION_PREFIX = f"{API_PREFIX}/intersection"

SIMULATION_TICK_SECONDS = 0.1
MIN_CYCLE_DURATION = 30
MAX_CYCLE_DURATION = 300
MAX_SIMULATION_DURATION = 3600
